apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30052
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
