apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo
  name: argo
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argo
  type: NodePort
